[package]
name = "treedect"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
env_logger = "0.11.8"
futures = "0.3.31"
image = "0.25.9"
log = "0.4.29"
rfd = "0.16.0"
tokio = { version = "1.0", features = ["full"] }
